reorder_imports = true
merge_derives = true
max_width = 100
fn_call_width = 100
attr_fn_like_width = 100
struct_lit_width = 100
struct_variant_width = 100
array_width = 100
chain_width = 100
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
use_small_heuristics = "Max"
