//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "claw_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub pem: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::claw::Entity",
        from = "Column::Id",
        to = "super::claw::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Claw,
}

impl Related<super::claw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Claw.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
