//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "claw")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub data: String,
    pub md5hash: String,
    pub validity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::claw_keys::Entity")]
    ClawKeys,
}

impl Related<super::claw_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClawKeys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
